# Generated by Django 5.0 on 2024-01-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_create_date_alter_post_create_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="create_date",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="create_date",
            new_name="created_date",
        ),
    ]
